import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
/**
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};
 */

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      id: 'index', // Home
      label: 'Home',
    },
    {
      type: 'doc',
      id: 'get-help',
    },
    {
      type: 'category',
      label: 'Release notes',
      items: [
        {
          type: 'doc',
          id: 'release-notes',
          label: 'Release notes index',
        },
        '2.7.3',
        '2.7.1-1',
        '2.7.1',
        '2.6.5',
        '2.6.3',
        '2.6.2',
        '2.5.5-1.2',
        {
          type: 'category',
          label: '2023 (versions 2.5.5 - 2.4.7)',
          items: [
            '2.5.5',
            '2.5.4',
            '2.5.3',
            '2.5.2',
            '2.5.1',
            '2.4.8',
            '2.4.7',
          ],
        },
        {
          type: 'category',
          label: '2022 - 2019 (versions 2.4.4-1.2 - 2.3.2-1)',
          items: [
            '2.4.4-1.2',
            '2.4.4',
            '2.4.3',
            '2.4.2',
            'release-notes-2.3.2-1',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'ProxySQL and admin tools',
      items: [
        {
          type: 'category',
          label: 'Install',
          items: [
            'where-to-download-proxysql',
            'install-v2',
            'install-proxysql2-tarball',
            'build-psh',
          ],
        },
        {
          type: 'category',
          label: 'Deploy',
          items: [
            'start-or-stop-proxysql2',
            'upgrade-proxysql2',
            'uninstall-proxysql2',
          ],
        },
        {
          type: 'category',
          label: 'proxysql-admin',
          items: [
            {
              type: 'category',
              label: 'Manage',
              items: [
                'proxysql-admin-tool-changes',
                'proxysql-admin-tool-v2-config',
                'proxysql-admin-tool-functions',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'pxc_scheduler_handler',
          items: [
            {
              type: 'category',
              label: 'Manage',
              items: [
                'psh-overview',
                'psh-configuration',
                'psh-options',
                'psh-detailed-options',
                'psh-known-limitations',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'trademark-policy',
        'copyright-and-licensing-information',
      ],
    },
  ],
};

export default sidebars;
